// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwnpoudlfrjnfovmuqxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3bnBvdWRsZnJqbmZvdm11cXhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODg2MzAsImV4cCI6MjA2NTU2NDYzMH0.ps1pxAINVMO1Vr8Of9RJgtD7BIbMoF-AZwkBMZJfA8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);